### PR TITLE
Init raspberry test chapter

### PR DESCRIPTION
**Pull request by piotrdanio**

### CODE REVIEW

**Comment by acwiek** [comment]
@piotrdanio what about the conversations mentioned above? Are all of them resolved?

**Comment by acwiek** [comment]
please replace `<br /><br />` with new lines

**Comment by acwiek** [comment]
From what I heard, Macies said, that you should cherry-pick commits from this PR on another branch, to make them all be verified.
On the other hand, last 4 commits introduce unwanted changes - check diff

**Comment by piotrdanio** [comment]
All upper commits were moved by cherry-pick comment into the new branch RaspberryTest2. Unverified commits could be deleted.

**Comment by piotrdanio** [comment]
This chapter is added to the main

**Pull request closed without merging**
