### PR TITLE
Add missing instrument patch

### PR DESCRIPTION
**Pull request by piotrdanio**
This commit add instrument patch which was removed by mistake.

### CODE REVIEW

**Comment by acwiek** [comment]
Maybe use this commit to also fix formatting issues in journal.md that was introduced by unwanted merge request

**Review by acwiek — COMMENTED** [review]
Did you check if the instrument.patch is still applicable using git commands?

**Comment by macpijan** [comment]
@piotrdanio We asked for fixing unverified and it did not happen. You also have not answered to Adam's comment from two weeks.

**Comment by macpijan** [comment]
@piotrdanio Please also work on the commit messages. They are not descriptive enough and do not meet our guidelines.

 I fixed some of these to move forward. If there is a need to update the patch, use another PR.

**Pull request merged**
