### PR TITLE
journal.md updated

### PR DESCRIPTION
**Pull request by acwiek**

### CODE REVIEW

**Comment by macpijan** [comment]
@acwiek Small conflict to be resolved before merging is allowed

**Comment by acwiek** [comment]
Conflict resolved

**Comment by macpijan** [comment]
@acwiek Sorry but we have once again. We had some mess with this journal move probably

**Comment by acwiek** [comment]
No problem. I think it should be ok now.

**Comment by macpijan** [comment]
It is, thanks

**Review by macpijan — APPROVED** [review]

**Pull request merged**
